In [1]:
import os
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as pulse

In [2]:

# path to your raw df folder
path = r"C:\Users\Admin\Desktop\sb\ds_ml\internship\labmentix\project_2\raw_data_frames"

# store all dfs in a dictionary
dfs = {}

for file in os.listdir(path):
    if file.endswith(".csv"):
        name = file.replace(".csv", "")
        dfs[name] = pd.read_csv(os.path.join(path, file))

# check what loaded
for name, df in dfs.items():
    print(name, df.shape)

df_aggregated_insurance_state (682, 5)
df_aggregated_insurance_years (19, 4)
df_aggregated_transaction_state (5034, 5)
df_aggregated_transaction_years (140, 4)
df_aggregated_user_state (6732, 7)
df_aggregated_user_years (187, 6)
df_map_insurance_country_state (1043137, 6)
df_map_insurance_country_years (387212, 5)
df_map_insurance_hover_state (13876, 6)
df_map_insurance_hover_years (682, 5)
df_map_transaction_state (20604, 5)
df_map_transaction_years (1008, 5)
df_map_user_state (20608, 5)
df_map_user_years (1008, 4)
df_top_insurance_state (12276, 7)
df_top_insurance_years (570, 6)
df_top_transaction_state (18295, 7)
df_top_transaction_years (280, 5)
df_top_user_state (18296, 5)
df_top_user_years (840, 4)

In [3]:
for name, df in dfs.items():
    globals()[name] = df

In [4]:
df_map_insurance_country_state.duplicated().sum()

np.int64(45393)

In [5]:
# Remove problematic DataFrames
dfs.pop("df_map_insurance_country_state", None)
dfs.pop("df_map_insurance_country_years", None)

print("Removed unwanted DataFrames successfully!")
print("Remaining DataFrames:", list(dfs.keys()))

Removed unwanted DataFrames successfully!
Remaining DataFrames: ['df_aggregated_insurance_state', 'df_aggregated_insurance_years', 'df_aggregated_transaction_state', 'df_aggregated_transaction_years', 'df_aggregated_user_state', 'df_aggregated_user_years', 'df_map_insurance_hover_state', 'df_map_insurance_hover_years', 'df_map_transaction_state', 'df_map_transaction_years', 'df_map_user_state', 'df_map_user_years', 'df_top_insurance_state', 'df_top_insurance_years', 'df_top_transaction_state', 'df_top_transaction_years', 'df_top_user_state', 'df_top_user_years']

In [6]:
for name, df in dfs.items():
    print(f"\n{name} — Null values:")
    print(df.isnull().sum())
    print("-" * 50)

df_aggregated_insurance_state — Null values:
state               0
year                0
transaction_type    0
count               0
amount              0
dtype: int64
--------------------------------------------------

df_aggregated_insurance_years — Null values:
Year                0
Transaction_Type    0
Count               0
Amount              0
dtype: int64
--------------------------------------------------

df_aggregated_transaction_state — Null values:
state               0
year                0
transaction_type    0
count               0
amount              0
dtype: int64
--------------------------------------------------

df_aggregated_transaction_years — Null values:
Year                0
Transaction_Type    0
Count               0
Amount              0
dtype: int64
--------------------------------------------------

df_aggregated_user_state — Null values:
state               0
year                0
brand               0
count               0
percentage          0
registered_users    0
app_opens           0
dtype: int64
--------------------------------------------------

df_aggregated_user_years — Null values:
year                0
brand               0
count               0
percentage          0
registered_users    0
app_opens           0
dtype: int64
--------------------------------------------------

df_map_insurance_hover_state — Null values:
state          0
year           0
district       0
metric_type    0
count          0
amount         0
dtype: int64
--------------------------------------------------

df_map_insurance_hover_years — Null values:
state          0
year           0
metric_type    0
count          0
amount         0
dtype: int64
--------------------------------------------------

df_map_transaction_state — Null values:
state               0
year                0
transaction_type    0
count               0
amount              0
dtype: int64
--------------------------------------------------

df_map_transaction_years — Null values:
year           0
state          0
metric_type    0
count          0
amount         0
dtype: int64
--------------------------------------------------

df_map_user_state — Null values:
state               0
year                0
district            0
registered_users    0
app_opens           0
dtype: int64
--------------------------------------------------

df_map_user_years — Null values:
state               0
year                0
registered_users    0
app_opens           0
dtype: int64
--------------------------------------------------

df_top_insurance_state — Null values:
state          0
year           0
level          0
entity_name    3
metric_type    0
count          0
amount         0
dtype: int64
--------------------------------------------------

df_top_insurance_years — Null values:
year           0
level          0
entity_name    0
metric_type    0
count          0
amount         0
dtype: int64
--------------------------------------------------

df_top_transaction_state — Null values:
state          0
year           0
level          0
entity_name    2
metric_type    0
count          0
amount         0
dtype: int64
--------------------------------------------------

df_top_transaction_years — Null values:
year           0
state          0
metric_type    0
count          0
amount         0
dtype: int64
--------------------------------------------------

df_top_user_state — Null values:
state               0
year                0
level               0
entity_name         0
registered_users    0
dtype: int64
--------------------------------------------------

df_top_user_years — Null values:
year                0
level               0
entity_name         0
registered_users    0
dtype: int64
--------------------------------------------------

In [7]:
for name, df in dfs.items():
    dup_count = df.duplicated().sum()
    print(f"{name}: {dup_count} duplicate rows")

df_aggregated_insurance_state: 0 duplicate rows
df_aggregated_insurance_years: 0 duplicate rows
df_aggregated_transaction_state: 0 duplicate rows
df_aggregated_transaction_years: 0 duplicate rows
df_aggregated_user_state: 0 duplicate rows
df_aggregated_user_years: 0 duplicate rows
df_map_insurance_hover_state: 1 duplicate rows
df_map_insurance_hover_years: 0 duplicate rows
df_map_transaction_state: 0 duplicate rows
df_map_transaction_years: 0 duplicate rows
df_map_user_state: 0 duplicate rows
df_map_user_years: 0 duplicate rows
df_top_insurance_state: 0 duplicate rows
df_top_insurance_years: 0 duplicate rows
df_top_transaction_state: 0 duplicate rows
df_top_transaction_years: 0 duplicate rows
df_top_user_state: 2 duplicate rows
df_top_user_years: 0 duplicate rows

In [8]:
for name, df in dfs.items():
    df.drop_duplicates(inplace=True)

In [9]:
for name, df in dfs.items():
    dup_count = df.duplicated().sum()
    print(f"{name}: {dup_count} duplicate rows")

df_aggregated_insurance_state: 0 duplicate rows
df_aggregated_insurance_years: 0 duplicate rows
df_aggregated_transaction_state: 0 duplicate rows
df_aggregated_transaction_years: 0 duplicate rows
df_aggregated_user_state: 0 duplicate rows
df_aggregated_user_years: 0 duplicate rows
df_map_insurance_hover_state: 0 duplicate rows
df_map_insurance_hover_years: 0 duplicate rows
df_map_transaction_state: 0 duplicate rows
df_map_transaction_years: 0 duplicate rows
df_map_user_state: 0 duplicate rows
df_map_user_years: 0 duplicate rows
df_top_insurance_state: 0 duplicate rows
df_top_insurance_years: 0 duplicate rows
df_top_transaction_state: 0 duplicate rows
df_top_transaction_years: 0 duplicate rows
df_top_user_state: 0 duplicate rows
df_top_user_years: 0 duplicate rows

In [10]:
for name, df in dfs.items():
    print(f"\n{name}")
    print(df.info())
    print(df.describe(include='all').T.head(),'\n\n\n\n\n\n\n')  # quick stats

df_aggregated_insurance_state
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             682 non-null    object
 1   year              682 non-null    int64
 2   transaction_type  682 non-null    object
 3   count             682 non-null    int64
 4   amount            682 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 26.8+ KB
None
                  count unique                        top freq  \
state               682     36  andaman-&-nicobar-islands   19
year              682.0    NaN                        NaN  NaN
transaction_type    682      1                  Insurance  682
count             682.0    NaN                        NaN  NaN
amount            682.0    NaN                        NaN  NaN

                            mean              std     min       25%  \
state                        NaN              NaN     NaN       NaN
year                 2022.111437          1.37073  2020.0    2021.0
transaction_type             NaN              NaN     NaN       NaN
count               21283.998534     31503.745791     4.0    607.75
amount            29348355.40176  47630854.450354  1199.0  821147.5

                        50%          75%          max
state                   NaN          NaN          NaN
year                 2022.0       2023.0       2024.0
transaction_type        NaN          NaN          NaN
count                6679.5      29790.5     183532.0
amount            6675645.0  37306845.75  305861806.0








df_aggregated_insurance_years
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              19 non-null     int64
 1   Transaction_Type  19 non-null     object
 2   Count             19 non-null     int64
 3   Amount            19 non-null     float64
dtypes: float64(1), int64(2), object(1)
memory usage: 740.0+ bytes
None
                 count unique        top freq               mean  \
Year              19.0    NaN        NaN  NaN        2022.105263
Transaction_Type    19      1  Insurance   19                NaN
Count             19.0    NaN        NaN  NaN      763998.105263
Amount            19.0    NaN        NaN  NaN  1053469464.157895

                               std         min          25%           50%  \
Year                      1.410072      2020.0       2021.0        2022.0
Transaction_Type               NaN         NaN          NaN           NaN
Count                393916.149753    185348.0     369428.0      806491.0
Amount            727500872.345584  33732166.0  318735015.0  1054717869.0

                           75%           max
Year                    2023.0        2024.0
Transaction_Type           NaN           NaN
Count                1070202.5     1475429.0
Amount            1602431287.0  2293956286.0








df_aggregated_transaction_state
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5034 entries, 0 to 5033
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             5034 non-null   object
 1   year              5034 non-null   int64
 2   transaction_type  5034 non-null   object
 3   count             5034 non-null   int64
 4   amount            5034 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 196.8+ KB
None
                   count unique                        top  freq  \
state               5034     36  andaman-&-nicobar-islands   140
year              5034.0    NaN                        NaN   NaN
transaction_type    5034      5   Recharge & bill payments  1008
count             5034.0    NaN                        NaN   NaN
amount            5034.0    NaN                        NaN   NaN

                                mean                  std        min  \
state                            NaN                  NaN        NaN
year                     2021.002582             1.999849     2018.0
transaction_type                 NaN                  NaN        NaN
count                46739018.052046     169096816.568642        2.0
amount            68637722454.387466  268519963110.148895  34.397212

                              25%               50%                 75%  \
state                         NaN               NaN                 NaN
year                       2019.0            2021.0              2023.0
transaction_type              NaN               NaN                 NaN
count                     58089.5          515831.0         11666286.25
amount            39938879.642835  439413884.614912  11028222171.778061

                              max
state                         NaN
year                       2024.0
transaction_type              NaN
count                2393917535.0
amount            3095666288407.0








df_aggregated_transaction_years
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Year              140 non-null    int64
 1   Transaction_Type  140 non-null    object
 2   Count             140 non-null    int64
 3   Amount            140 non-null    float64
dtypes: float64(1), int64(2), object(1)
memory usage: 4.5+ KB
None
                  count unique                       top freq  \
Year              140.0    NaN                       NaN  NaN
Transaction_Type    140      5  Recharge & bill payments   28
Count             140.0    NaN                       NaN  NaN
Amount            140.0    NaN                       NaN  NaN

                                  mean                   std  \
Year                            2021.0              2.007181
Transaction_Type                   NaN                   NaN
Count                1680606461.221429     3302733845.239445
Amount            2468027006208.040039  5397845572479.836914

                               min            25%                 50%  \
Year                        2018.0         2019.0              2021.0
Transaction_Type               NaN            NaN                 NaN
Count                    1358171.0     8441505.75         204244384.5
Amount            545329308.089986  6384408755.75  119777197364.35556

                                   75%               max
Year                            2023.0            2024.0
Transaction_Type                   NaN               NaN
Count                     1372036016.5     17419191808.0
Amount            1430352296955.341797  26633866936498.0








df_aggregated_user_state
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6732 entries, 0 to 6731
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             6732 non-null   object
 1   year              6732 non-null   int64
 2   brand             6732 non-null   object
 3   count             6732 non-null   int64
 4   percentage        6732 non-null   float64
 5   registered_users  6732 non-null   int64
 6   app_opens         6732 non-null   int64
dtypes: float64(1), int64(4), object(2)
memory usage: 368.3+ KB
None
             count unique                        top freq           mean  \
state         6732     36  andaman-&-nicobar-islands  187            NaN
year        6732.0    NaN                        NaN  NaN    2019.647059
brand         6732     20                     Xiaomi  612            NaN
count       6732.0    NaN                        NaN  NaN  514011.466429
percentage  6732.0    NaN                        NaN  NaN       0.090909

                       std       min       25%       50%        75%  \
state                  NaN       NaN       NaN       NaN        NaN
year              1.233984    2018.0    2019.0    2020.0     2021.0
brand                  NaN       NaN       NaN       NaN        NaN
count       1081772.126452      10.0    9354.0   84722.5  455580.75
percentage        0.083401  0.005158  0.020513  0.057718   0.146007

                   max
state              NaN
year            2022.0
brand              NaN
count       11340940.0
percentage    0.478367








df_aggregated_user_years
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   year              187 non-null    int64
 1   brand             187 non-null    object
 2   count             187 non-null    int64
 3   percentage        187 non-null    float64
 4   registered_users  187 non-null    int64
 5   app_opens         187 non-null    int64
dtypes: float64(1), int64(4), object(1)
memory usage: 8.9+ KB
None
                  count unique     top freq              mean  \
year              187.0    NaN     NaN  NaN       2019.647059
brand               187     12  Xiaomi   17               NaN
count             187.0    NaN     NaN  NaN   18504477.326203
percentage        187.0    NaN     NaN  NaN          0.090909
registered_users  187.0    NaN     NaN  NaN  203549250.588235

                               std         min          25%          50%  \
year                      1.237205      2018.0       2019.0       2020.0
brand                          NaN         NaN          NaN          NaN
count              20606424.961753    808774.0    4016112.5    8103650.0
percentage                 0.08033     0.01082     0.022157     0.053561
registered_users  100528543.805995  46877867.0  123432699.0  197575164.0

                          75%          max
year                   2021.0       2022.0
brand                     NaN          NaN
count              25716819.5   88426997.0
percentage           0.149248     0.261188
registered_users  284985430.0  372951831.0








df_map_insurance_hover_state
<class 'pandas.core.frame.DataFrame'>
Index: 13875 entries, 0 to 13875
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        13875 non-null  object
 1   year         13875 non-null  int64
 2   district     13875 non-null  object
 3   metric_type  13875 non-null  object
 4   count        13875 non-null  int64
 5   amount       13875 non-null  float64
dtypes: float64(1), int64(2), object(3)
memory usage: 758.8+ KB
None
               count unique                top   freq         mean  \
state          13875     36      uttar-pradesh   1427          NaN
year         13875.0    NaN                NaN    NaN  2022.133838
district       13875    842  hamirpur district     38          NaN
metric_type    13875      1              TOTAL  13875          NaN
count        13875.0    NaN                NaN    NaN  1046.175568

                     std     min     25%     50%     75%      max
state                NaN     NaN     NaN     NaN     NaN      NaN
year            1.375522  2020.0  2021.0  2022.0  2023.0   2024.0
district             NaN     NaN     NaN     NaN     NaN      NaN
metric_type          NaN     NaN     NaN     NaN     NaN      NaN
count        3131.742911     1.0   113.0   332.0   909.0  96935.0








df_map_insurance_hover_years
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 682 entries, 0 to 681
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        682 non-null    object
 1   year         682 non-null    int64
 2   metric_type  682 non-null    object
 3   count        682 non-null    int64
 4   amount       682 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 26.8+ KB
None
             count unique         top freq            mean              std  \
state          682     36  puducherry   19             NaN              NaN
year         682.0    NaN         NaN  NaN     2022.111437          1.37073
metric_type    682      1       TOTAL  682             NaN              NaN
count        682.0    NaN         NaN  NaN    21283.998534     31503.745791
amount       682.0    NaN         NaN  NaN  29348355.40176  47630854.450354

                min       25%        50%          75%          max
state           NaN       NaN        NaN          NaN          NaN
year         2020.0    2021.0     2022.0       2023.0       2024.0
metric_type     NaN       NaN        NaN          NaN          NaN
count           4.0    607.75     6679.5      29790.5     183532.0
amount       1199.0  821147.5  6675645.0  37306845.75  305861806.0








df_map_transaction_state
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20604 entries, 0 to 20603
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             20604 non-null  object
 1   year              20604 non-null  int64
 2   transaction_type  20604 non-null  object
 3   count             20604 non-null  int64
 4   amount            20604 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 805.0+ KB
None
                    count unique            top   freq                mean  \
state               20604     36  uttar-pradesh   2100                 NaN
year              20604.0    NaN            NaN    NaN          2021.01689
transaction_type    20604      1          TOTAL  20604                 NaN
count             20604.0    NaN            NaN    NaN     11419346.577072
amount            20604.0    NaN            NaN    NaN  16769670687.021288

                                std         min               25%  \
state                           NaN         NaN               NaN
year                       2.006519      2018.0            2019.0
transaction_type                NaN         NaN               NaN
count               45345702.315765         2.0          252145.5
amount            56556397602.96389  169.888565  457829150.684471

                                50%                 75%              max
state                           NaN                 NaN              NaN
year                         2021.0              2023.0           2024.0
transaction_type                NaN                 NaN              NaN
count                     1558070.0          8122777.25     1674347983.0
amount            2868917883.306988  13524227543.504625  1790144192589.0








df_map_transaction_years
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         1008 non-null   int64
 1   state        1008 non-null   object
 2   metric_type  1008 non-null   object
 3   count        1008 non-null   int64
 4   amount       1008 non-null   float64
dtypes: float64(1), int64(2), object(2)
memory usage: 39.5+ KB
None
              count unique         top  freq                 mean  \
year         1008.0    NaN         NaN   NaN               2021.0
state          1008     36  puducherry    28                  NaN
metric_type    1008      1       TOTAL  1008                  NaN
count        1008.0    NaN         NaN   NaN     233416881.819444
amount       1008.0    NaN         NaN   NaN  342780054400.183777

                             std             min                25%  \
year                    2.000993          2018.0             2019.0
state                        NaN             NaN                NaN
metric_type                  NaN             NaN                NaN
count           514372084.866039           778.0         2072062.25
amount       703028813261.481201  1928611.180878  4434177031.711637

                            50%                 75%              max
year                     2021.0              2023.0           2024.0
state                       NaN                 NaN              NaN
metric_type                 NaN                 NaN              NaN
count                17993643.0         177512117.0     3634231839.0
amount       29518221935.592026  281215511697.05481  4151819803822.0








df_map_user_state
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20608 entries, 0 to 20607
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             20608 non-null  object
 1   year              20608 non-null  int64
 2   district          20608 non-null  object
 3   registered_users  20608 non-null  int64
 4   app_opens         20608 non-null  int64
dtypes: int64(3), object(2)
memory usage: 805.1+ KB
None
                    count unique                top  freq             mean  \
state               20608     36      uttar-pradesh  2100              NaN
year              20608.0    NaN                NaN   NaN      2021.016304
district            20608    843  bilaspur district    56              NaN
registered_users  20608.0    NaN                NaN   NaN    430133.776106
app_opens         20608.0    NaN                NaN   NaN  19520970.245924

                              std     min       25%        50%         75%  \
state                         NaN     NaN       NaN        NaN         NaN
year                     2.006764  2018.0    2019.0     2021.0      2023.0
district                      NaN     NaN       NaN        NaN         NaN
registered_users     814849.23761    22.0  62085.25   199532.0   489604.75
app_opens         40040473.908591     0.0  483938.5  5946804.0  21915294.5

                           max
state                      NaN
year                    2024.0
district                   NaN
registered_users    18127475.0
app_opens         1137875291.0








df_map_user_years
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   state             1008 non-null   object
 1   year              1008 non-null   int64
 2   registered_users  1008 non-null   int64
 3   app_opens         1008 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.6+ KB
None
                   count unique         top freq              mean  \
state               1008     36  puducherry   28               NaN
year              1008.0    NaN         NaN  NaN            2021.0
registered_users  1008.0    NaN         NaN  NaN    8793846.089286
app_opens         1008.0    NaN         NaN  NaN  399095391.694444

                               std     min        25%         50%  \
state                          NaN     NaN        NaN         NaN
year                      2.000993  2018.0     2019.0      2021.0
registered_users   12563745.037582   501.0   306702.0   2920231.5
app_opens         802611106.175276     0.0  1965471.5  41911496.0

                          75%           max
state                     NaN           NaN
year                   2023.0        2024.0
registered_users  12872699.25    71807805.0
app_opens         368482035.5  5335171033.0








df_top_insurance_state
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12276 entries, 0 to 12275
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   state        12276 non-null  object
 1   year         12276 non-null  int64
 2   level        12276 non-null  object
 3   entity_name  12273 non-null  object
 4   metric_type  12276 non-null  object
 5   count        12276 non-null  int64
 6   amount       12276 non-null  float64
dtypes: float64(1), int64(2), object(4)
memory usage: 671.5+ KB
None
               count unique             top   freq         mean       std  \
state          12276     36  andhra-pradesh    380          NaN       NaN

In [11]:
dfs["df_aggregated_user_state"][["registered_users", "app_opens"]].dtypes

registered_users    int64
app_opens           int64
dtype: object

In [12]:
df = dfs["df_aggregated_user_state"]
print(df["registered_users"].unique()[:10])  # see first 10 unique values
print(df["app_opens"].unique()[:10])

[ 6740  9405 12149 15222 18596 21731 23931 25960 28368 32710]
[      0   52640  171107  177012  193586  305072  515565  887208 1004336
 2248223]

In [13]:
dfs["df_aggregated_user_state"][["registered_users", "app_opens"]].describe()

       registered_users     app_opens
count      6.732000e+03  6.732000e+03
mean       5.654126e+06  1.510069e+08
std        7.955764e+06  3.236699e+08
min        5.010000e+02  0.000000e+00
25%        1.918582e+05  0.000000e+00
50%        1.978676e+06  5.893784e+06
75%        8.393058e+06  1.496510e+08
max        4.822763e+07  2.570606e+09

In [14]:
df_top_user_state.head(10)

,state,year,level,entity_name,registered_users
0,andaman-&-nicobar-islands,2018,district,south andaman,5846
1,andaman-&-nicobar-islands,2018,district,north and middle andaman,632
2,andaman-&-nicobar-islands,2018,district,nicobars,262
3,andaman-&-nicobar-islands,2018,pincode,744103,1608
4,andaman-&-nicobar-islands,2018,pincode,744101,1108
5,andaman-&-nicobar-islands,2018,pincode,744105,1075
6,andaman-&-nicobar-islands,2018,pincode,744102,1006
7,andaman-&-nicobar-islands,2018,pincode,744104,272
8,andaman-&-nicobar-islands,2018,pincode,744202,237
9,andaman-&-nicobar-islands,2018,pincode,744112,215

In [15]:
df_top_user_years.tail(10)

     year    level entity_name  registered_users
830  2024  pincode      201301            964283
831  2024  pincode      421302            871910
832  2024  pincode      110059            826819
833  2024  pincode      500072            755978
834  2024  pincode      452001            709324
835  2024  pincode      410501            683435
836  2024  pincode      560068            663903
837  2024  pincode      121004            661818
838  2024  pincode      201009            660474
839  2024  pincode      110092            654020

In [16]:
for name, df in dfs.items():
    print(f"\n===== {name} =====")
    display(df.sample(5))

===== df_aggregated_insurance_state =====

            state  year transaction_type  count       amount
66          assam  2022        Insurance  14149   22543564.0
385   maharashtra  2022        Insurance  88015  117411928.0
225       haryana  2024        Insurance  46085   74779879.0
400       manipur  2021        Insurance    136      72254.0
118  chhattisgarh  2021        Insurance   5055    3813417.0

===== df_aggregated_insurance_years =====

    Year Transaction_Type    Count        Amount
7   2022        Insurance   617606  8.874472e+08
1   2020        Insurance   354284  8.949508e+07
10  2022        Insurance  1035364  1.439763e+09
14  2023        Insurance  1159063  1.855300e+09
8   2022        Insurance   630758  8.570348e+08

===== df_aggregated_transaction_state =====

,state,year,transaction_type,count,amount
407,arunachal-pradesh,2024,Recharge & bill payments,1776684,5.959576e+08
3920,rajasthan,2018,Peer-to-peer payments,3770555,1.334159e+10
3967,rajasthan,2020,Financial Services,146383,1.136751e+08
4246,tamil-nadu,2020,Recharge & bill payments,17521756,7.476952e+09
1993,jharkhand,2019,Financial Services,103620,8.027639e+07

===== df_aggregated_transaction_years =====

     Year       Transaction_Type      Count        Amount
114  2023                 Others    8491944  6.397985e+09
30   2019  Peer-to-peer payments  461911865  1.440513e+12
14   2018                 Others    5594554  4.449556e+09
119  2023                 Others    8651416  6.391200e+09
98   2022     Financial Services    4623387  5.360528e+09

===== df_aggregated_user_state =====

,state,year,brand,count,percentage,registered_users,app_opens
1349,dadra-&-nagar-haveli-&-daman-&-diu,2018,Apple,2546,0.021852,116511,0
5633,tamil-nadu,2018,Samsung,739663,0.189649,3900177,0
2095,haryana,2018,Realme,179167,0.047235,3793079,0
837,bihar,2020,Samsung,1896957,0.202856,9351234,183868505
4235,meghalaya,2020,Xiaomi,41993,0.237992,176447,2745917

===== df_aggregated_user_years =====

     year     brand     count  percentage  registered_users    app_opens
114  2020    Realme  13737667    0.056963         241169683   5739326491
174  2021     Tecno   3799428    0.010820         351161395  15172529039
127  2020  Motorola   5650618    0.021382         264271293   7461623162
121  2020    Xiaomi  66711711    0.252436         264271293   7461623162
35   2018      Vivo  14966905    0.146358         102262055            0

===== df_map_insurance_hover_state =====

                state  year           district metric_type  count     amount
6385   madhya-pradesh  2022      dhar district       TOTAL    304   411503.0
3113          gujarat  2021     morbi district       TOTAL    173   144469.0
13793     west-bengal  2024  jhargram district       TOTAL    360   516844.0
1268            assam  2024   darrang district       TOTAL    856  1033170.0
7168      maharashtra  2021   hingoli district       TOTAL    150    96533.0

===== df_map_insurance_hover_years =====

         state  year metric_type  count      amount
519  jharkhand  2023       TOTAL  22398  33484644.0
242   nagaland  2021       TOTAL    183    341424.0
407  rajasthan  2023       TOTAL  34415  61441050.0
464      delhi  2023       TOTAL  41358  54951108.0
514    haryana  2023       TOTAL  47506  80747159.0

===== df_map_transaction_state =====

                  state  year transaction_type     count        amount
6005   himachal-pradesh  2019            TOTAL       897  2.325336e+06
18243     uttar-pradesh  2020            TOTAL    900026  1.541977e+09
3090              bihar  2024            TOTAL  15650940  2.283348e+10
6742    jammu-&-kashmir  2023            TOTAL   1057703  1.040759e+09
16070        tamil-nadu  2023            TOTAL   6134683  9.921813e+09

===== df_map_transaction_years =====

      year             state metric_type      count        amount
822   2023      chhattisgarh       TOTAL  283492657  3.503797e+11
882   2024            odisha       TOTAL  864178452  1.156389e+12
607   2022   jammu & kashmir       TOTAL   16245311  3.314786e+10
924   2024  himachal pradesh       TOTAL   52583801  5.984974e+10
1004  2024               goa       TOTAL   46131536  5.656259e+10

===== df_map_user_state =====

                state  year             district  registered_users  app_opens
194    andhra-pradesh  2020      guntur district           1289678   45282758
19525   uttar-pradesh  2024      amethi district            401383   28967921
5494          haryana  2019   faridabad district            862595   19751979
10643     maharashtra  2019      satara district            508340    9298809
15778      tamil-nadu  2021  viluppuram district            287910    5813660

===== df_map_user_years =====

                 state  year  registered_users  app_opens
726        lakshadweep  2023              7267      43821
127              bihar  2018           4776665          0
455          telangana  2021          17149069  920040042
658          meghalaya  2022            283487   32596135
573  arunachal pradesh  2021            314944   11230295

===== df_top_insurance_state =====

,state,year,level,entity_name,metric_type,count,amount
8783,puducherry,2021,district,yanam,TOTAL,8,3551.0
5006,jharkhand,2024,district,dhanbad,TOTAL,2818,3833061.0
11927,west-bengal,2020,pincode,700091,TOTAL,103,30050.0
4486,jammu-&-kashmir,2022,district,kathua,TOTAL,342,529015.0
5997,ladakh,2023,pincode,194105,TOTAL,5,18413.0

===== df_top_insurance_years =====

     year     level entity_name metric_type  count       amount
465  2024  district  rangareddy       TOTAL  16320   28043767.0
279  2022     state     haryana       TOTAL  35346   45402800.0
514  2024     state      kerala       TOTAL  79123  131721699.0
461  2024  district        pune       TOTAL  31744   51048763.0
232  2022   pincode      560043       TOTAL   1713    2402868.0

===== df_top_transaction_state =====

,state,year,level,entity_name,metric_type,count,amount
16604,tripura,2024,district,khowai,TOTAL,735106,1.084422e+09
916,andhra-pradesh,2024,pincode,520007,TOTAL,19533453,2.849731e+10
9421,madhya-pradesh,2020,district,sehore,TOTAL,2512141,4.197137e+09
27,andaman-&-nicobar-islands,2018,district,nicobars,TOTAL,1471,6.387829e+06
17618,uttarakhand,2023,district,nainital,TOTAL,8620296,1.103526e+10

===== df_top_transaction_years =====

     year           state metric_type       count        amount
87   2020  madhya pradesh       TOTAL    79366746  1.267373e+11
233  2023  andhra pradesh       TOTAL  1596987426  2.802515e+12
130  2021     maharashtra       TOTAL   573616486  9.151151e+11
279  2024          odisha       TOTAL  1143097568  1.305458e+12
194  2022       rajasthan       TOTAL   865574848  1.456957e+12

===== df_top_user_state =====

                state  year     level entity_name  registered_users
7025        jharkhand  2018   pincode      834005             20264
508    andhra-pradesh  2019  district    chittoor           1156351
14424       rajasthan  2022  district     udaipur            949767
9854      maharashtra  2018   pincode      411028             88343
11009       meghalaya  2019   pincode      793101              3703

===== df_top_user_years =====

     year     level                 entity_name  registered_users
164  2019  district                       thane           2118406
334  2020     state                   rajasthan          16329494
678  2023  district  north twenty four parganas           4241525
325  2020   pincode                      110092            314384
118  2018   pincode                      110086            133412

In [17]:
df_aggregated_insurance_state.transaction_type.unique()

array(['Insurance'], dtype=object)

In [18]:
for name, df in dfs.items():
    constant_cols = [col for col in df.columns if df[col].nunique() == 1]
    if constant_cols:
        print(f"{name}: dropping {constant_cols}")
        dfs[name] = df.drop(columns=constant_cols)

df_aggregated_insurance_state: dropping ['transaction_type']
df_aggregated_insurance_years: dropping ['Transaction_Type']

df_map_insurance_hover_state: dropping ['metric_type']
df_map_insurance_hover_years: dropping ['metric_type']
df_map_transaction_state: dropping ['transaction_type']
df_map_transaction_years: dropping ['metric_type']
df_top_insurance_state: dropping ['metric_type']
df_top_insurance_years: dropping ['metric_type']
df_top_transaction_state: dropping ['metric_type']
df_top_transaction_years: dropping ['metric_type']

In [19]:
for name, df in dfs.items():
    # Ensure all column names are strings before cleaning
    df.columns = df.columns.map(str)
    df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [20]:
for name, df in dfs.items():
    print(name,'\n',df.columns,'\n' )

df_aggregated_insurance_state
 Index(['state', 'year', 'count', 'amount'], dtype='object')

df_aggregated_insurance_years
 Index(['year', 'count', 'amount'], dtype='object')

df_aggregated_transaction_state
 Index(['state', 'year', 'transaction_type', 'count', 'amount'], dtype='object')

df_aggregated_transaction_years
 Index(['year', 'transaction_type', 'count', 'amount'], dtype='object')

df_aggregated_user_state
 Index(['state', 'year', 'brand', 'count', 'percentage', 'registered_users',
       'app_opens'],
      dtype='object')

df_aggregated_user_years
 Index(['year', 'brand', 'count', 'percentage', 'registered_users',
       'app_opens'],
      dtype='object')

df_map_insurance_hover_state
 Index(['state', 'year', 'district', 'count', 'amount'], dtype='object')

df_map_insurance_hover_years
 Index(['state', 'year', 'count', 'amount'], dtype='object')

df_map_transaction_state
 Index(['state', 'year', 'count', 'amount'], dtype='object')

df_map_transaction_years
 Index(['year', 'state', 'count', 'amount'], dtype='object')

df_map_user_state
 Index(['state', 'year', 'district', 'registered_users', 'app_opens'], dtype='object')

df_map_user_years
 Index(['state', 'year', 'registered_users', 'app_opens'], dtype='object')

df_top_insurance_state
 Index(['state', 'year', 'level', 'entity_name', 'count', 'amount'], dtype='object')

df_top_insurance_years
 Index(['year', 'level', 'entity_name', 'count', 'amount'], dtype='object')

df_top_transaction_state
 Index(['state', 'year', 'level', 'entity_name', 'count', 'amount'], dtype='object')

df_top_transaction_years
 Index(['year', 'state', 'count', 'amount'], dtype='object')

df_top_user_state
 Index(['state', 'year', 'level', 'entity_name', 'registered_users'], dtype='object')

df_top_user_years
 Index(['year', 'level', 'entity_name', 'registered_users'], dtype='object')

In [26]:
for name, df in dfs.items():
    print(f"{name}: {list(df.columns)}")
    print("-" * 110)

df_aggregated_insurance_state: ['state', 'year', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_aggregated_insurance_years: ['year', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_aggregated_transaction_state: ['state', 'year', 'transaction_type', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_aggregated_transaction_years: ['year', 'transaction_type', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_aggregated_user_state: ['state', 'year', 'brand', 'count', 'percentage', 'registered_users', 'app_opens']
--------------------------------------------------------------------------------------------------------------
df_aggregated_user_years: ['year', 'brand', 'count', 'percentage', 'registered_users', 'app_opens']
--------------------------------------------------------------------------------------------------------------
df_map_insurance_hover_state: ['state', 'year', 'district', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_map_insurance_hover_years: ['state', 'year', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_map_transaction_state: ['state', 'year', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_map_transaction_years: ['year', 'state', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_map_user_state: ['state', 'year', 'district', 'registered_users', 'app_opens']
--------------------------------------------------------------------------------------------------------------
df_map_user_years: ['state', 'year', 'registered_users', 'app_opens']
--------------------------------------------------------------------------------------------------------------
df_top_insurance_state: ['state', 'year', 'level', 'entity_name', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_top_insurance_years: ['year', 'level', 'entity_name', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_top_transaction_state: ['state', 'year', 'level', 'entity_name', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_top_transaction_years: ['year', 'state', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_top_user_state: ['state', 'year', 'level', 'entity_name', 'registered_users']
--------------------------------------------------------------------------------------------------------------
df_top_user_years: ['year', 'level', 'entity_name', 'registered_users']
--------------------------------------------------------------------------------------------------------------

In [29]:
for name, df in dfs.items():
    if "entity_name" in df.columns:
        df.rename(columns={"entity_name": "region"}, inplace=True)
    if "level" in df.columns:
        df.rename(columns={"level": "region_type"}, inplace=True)

In [30]:
for name, df in dfs.items():
    print(f"{name}: {list(df.columns)}")
    print("-" * 110)

df_aggregated_insurance_state: ['state', 'year', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_aggregated_insurance_years: ['year', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_aggregated_transaction_state: ['state', 'year', 'transaction_type', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_aggregated_transaction_years: ['year', 'transaction_type', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_aggregated_user_state: ['state', 'year', 'brand', 'count', 'percentage', 'registered_users', 'app_opens']
--------------------------------------------------------------------------------------------------------------
df_aggregated_user_years: ['year', 'brand', 'count', 'percentage', 'registered_users', 'app_opens']
--------------------------------------------------------------------------------------------------------------
df_map_insurance_hover_state: ['state', 'year', 'district', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_map_insurance_hover_years: ['state', 'year', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_map_transaction_state: ['state', 'year', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_map_transaction_years: ['year', 'state', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_map_user_state: ['state', 'year', 'district', 'registered_users', 'app_opens']
--------------------------------------------------------------------------------------------------------------
df_map_user_years: ['state', 'year', 'registered_users', 'app_opens']
--------------------------------------------------------------------------------------------------------------
df_top_insurance_state: ['state', 'year', 'region_type', 'region', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_top_insurance_years: ['year', 'region_type', 'region', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_top_transaction_state: ['state', 'year', 'region_type', 'region', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_top_transaction_years: ['year', 'state', 'count', 'amount']
--------------------------------------------------------------------------------------------------------------
df_top_user_state: ['state', 'year', 'region_type', 'region', 'registered_users']
--------------------------------------------------------------------------------------------------------------
df_top_user_years: ['year', 'region_type', 'region', 'registered_users']
--------------------------------------------------------------------------------------------------------------

In [ ]:
pd.set_option('display.width', 2000)      # or 0 for unlimited width
pd.set_option('display.max_columns', None)  # show all columns


# pd.reset_option('display.max_columns')
# pd.reset_option('display.width')

In [40]:
for name, df in dfs.items():
    print(f"\n{name} Summary:")
    print(df.describe().T)

df_aggregated_insurance_state Summary:
        count          mean           std     min        25%        50%          75%          max
year    682.0  2.022111e+03  1.370730e+00  2020.0    2021.00     2022.0      2023.00       2024.0
count   682.0  2.128400e+04  3.150375e+04     4.0     607.75     6679.5     29790.50     183532.0
amount  682.0  2.934836e+07  4.763085e+07  1199.0  821147.50  6675645.0  37306845.75  305861806.0

df_aggregated_insurance_years Summary:
        count          mean           std         min          25%           50%           75%           max
year     19.0  2.022105e+03  1.410072e+00      2020.0       2021.0  2.022000e+03  2.023000e+03  2.024000e+03
count    19.0  7.639981e+05  3.939161e+05    185348.0     369428.0  8.064910e+05  1.070202e+06  1.475429e+06
amount   19.0  1.053469e+09  7.275009e+08  33732166.0  318735015.0  1.054718e+09  1.602431e+09  2.293956e+09

df_aggregated_transaction_state Summary:
         count          mean           std          min           25%           50%           75%           max
year    5034.0  2.021003e+03  1.999849e+00  2018.000000  2.019000e+03  2.021000e+03  2.023000e+03  2.024000e+03
count   5034.0  4.673902e+07  1.690968e+08     2.000000  5.808950e+04  5.158310e+05  1.166629e+07  2.393918e+09
amount  5034.0  6.863772e+10  2.685200e+11    34.397212  3.993888e+07  4.394139e+08  1.102822e+10  3.095666e+12

df_aggregated_transaction_years Summary:
        count          mean           std           min           25%           50%           75%           max
year    140.0  2.021000e+03  2.007181e+00  2.018000e+03  2.019000e+03  2.021000e+03  2.023000e+03  2.024000e+03
count   140.0  1.680606e+09  3.302734e+09  1.358171e+06  8.441506e+06  2.042444e+08  1.372036e+09  1.741919e+10
amount  140.0  2.468027e+12  5.397846e+12  5.453293e+08  6.384409e+09  1.197772e+11  1.430352e+12  2.663387e+13

df_aggregated_user_state Summary:
                   count          mean           std          min            25%           50%           75%           max
year              6732.0  2.019647e+03  1.233984e+00  2018.000000    2019.000000  2.020000e+03  2.021000e+03  2.022000e+03
count             6732.0  5.140115e+05  1.081772e+06    10.000000    9354.000000  8.472250e+04  4.555808e+05  1.134094e+07
percentage        6732.0  9.090909e-02  8.340094e-02     0.005158       0.020513  5.771758e-02  1.460071e-01  4.783670e-01
registered_users  6732.0  5.654126e+06  7.955764e+06   501.000000  191858.250000  1.978676e+06  8.393058e+06  4.822763e+07
app_opens         6732.0  1.510069e+08  3.236699e+08     0.000000       0.000000  5.893784e+06  1.496510e+08  2.570606e+09

df_aggregated_user_years Summary:
                  count          mean           std           min           25%           50%           75%           max
year              187.0  2.019647e+03  1.237205e+00  2.018000e+03  2.019000e+03  2.020000e+03  2.021000e+03  2.022000e+03
count             187.0  1.850448e+07  2.060642e+07  8.087740e+05  4.016112e+06  8.103650e+06  2.571682e+07  8.842700e+07
percentage        187.0  9.090909e-02  8.033004e-02  1.081961e-02  2.215668e-02  5.356126e-02  1.492478e-01  2.611877e-01
registered_users  187.0  2.035493e+08  1.005285e+08  4.687787e+07  1.234327e+08  1.975752e+08  2.849854e+08  3.729518e+08
app_opens         187.0  5.436271e+09  5.182668e+09  0.000000e+00  0.000000e+00  4.357634e+09  8.635509e+09  1.572420e+10

df_map_insurance_hover_state Summary:
          count          mean           std     min       25%       50%        75%          max
year    13875.0  2.022134e+03  1.375522e+00  2020.0    2021.0    2022.0     2023.0       2024.0
count   13875.0  1.046176e+03  3.131743e+03     1.0     113.0     332.0      909.0      96935.0
amount  13875.0  1.442564e+06  4.503531e+06    31.0  105098.0  441520.0  1280082.5  159224823.0

df_map_insurance_hover_years Summary:
        count          mean           std     min        25%        50%          75%          max
year    682.0  2.022111e+03  1.370730e+00  2020.0    2021.00     2022.0      2023.00       2024.0
count   682.0  2.128400e+04  3.150375e+04     4.0     607.75     6679.5     29790.50     183532.0
amount  682.0  2.934836e+07  4.763085e+07  1199.0  821147.50  6675645.0  37306845.75  305861806.0

df_map_transaction_state Summary:
          count          mean           std          min           25%           50%           75%           max
year    20604.0  2.021017e+03  2.006519e+00  2018.000000  2.019000e+03  2.021000e+03  2.023000e+03  2.024000e+03
count   20604.0  1.141935e+07  4.534570e+07     2.000000  2.521455e+05  1.558070e+06  8.122777e+06  1.674348e+09
amount  20604.0  1.676967e+10  5.655640e+10   169.888565  4.578292e+08  2.868918e+09  1.352423e+10  1.790144e+12

df_map_transaction_years Summary:
         count          mean           std           min           25%           50%           75%           max
year    1008.0  2.021000e+03  2.000993e+00  2.018000e+03  2.019000e+03  2.021000e+03  2.023000e+03  2.024000e+03
count   1008.0  2.334169e+08  5.143721e+08  7.780000e+02  2.072062e+06  1.799364e+07  1.775121e+08  3.634232e+09
amount  1008.0  3.427801e+11  7.030288e+11  1.928611e+06  4.434177e+09  2.951822e+10  2.812155e+11  4.151820e+12

df_map_user_state Summary:
                    count          mean           std     min        25%        50%          75%           max
year              20608.0  2.021016e+03  2.006764e+00  2018.0    2019.00     2021.0      2023.00  2.024000e+03
registered_users  20608.0  4.301338e+05  8.148492e+05    22.0   62085.25   199532.0    489604.75  1.812748e+07
app_opens         20608.0  1.952097e+07  4.004047e+07     0.0  483938.50  5946804.0  21915294.50  1.137875e+09

df_map_user_years Summary:
                   count          mean           std     min        25%         50%           75%           max
year              1008.0  2.021000e+03  2.000993e+00  2018.0     2019.0      2021.0  2.023000e+03  2.024000e+03
registered_users  1008.0  8.793846e+06  1.256375e+07   501.0   306702.0   2920231.5  1.287270e+07  7.180780e+07
app_opens         1008.0  3.990954e+08  8.026111e+08     0.0  1965471.5  41911496.0  3.684820e+08  5.335171e+09

df_top_insurance_state Summary:
          count          mean           std     min       25%       50%         75%          max
year    12276.0  2.022118e+03  1.370013e+00  2020.0   2021.00    2022.0     2023.00       2024.0
count   12276.0  1.090690e+03  3.325674e+03     1.0     50.00     282.0      968.00      96935.0
amount  12276.0  1.457266e+06  4.781771e+06    31.0  55933.75  302106.0  1222879.75  159224823.0

df_top_insurance_years Summary:
        count          mean           std      min         25%        50%          75%          max
year    570.0  2.022105e+03  1.373669e+00   2020.0     2021.00     2022.0      2023.00       2024.0
count   570.0  2.508906e+04  3.354610e+04    465.0     2407.50    11772.5     34902.00     183532.0
amount  570.0  3.343041e+07  5.135445e+07  94570.0  2657362.75  9881336.5  40860231.75  305861806.0

df_top_transaction_state Summary:
          count          mean           std          min           25%           50%           75%           max
year    18295.0  2.021002e+03  2.000805e+00  2018.000000  2.019000e+03  2.021000e+03  2.023000e+03  2.024000e+03
count   18295.0  1.197467e+07  4.962090e+07     2.000000  1.222215e+05  9.845220e+05  6.708908e+06  1.674348e+09
amount  18295.0  1.690444e+10  6.277009e+10    60.252763  2.372684e+08  1.538457e+09  1.033093e+10  1.790144e+12

df_top_transaction_years Summary:
        count          mean           std           min           25%           50%           75%           max
year    280.0  2.021000e+03  2.003581e+00  2.018000e+03  2.019000e+03  2.021000e+03  2.023000e+03  2.024000e+03
count   280.0  6.709144e+08  7.949961e+08  6.726622e+06  7.598623e+07  3.212216e+08  1.014034e+09  3.634232e+09
amount  280.0  9.854321e+11  1.050465e+12  8.681603e+09  1.245471e+11  6.167836e+11  1.549236e+12  4.151820e+12

df_top_user_state Summary:
                    count           mean            std     min       25%       50%       75%         max
year              18294.0    2021.002241       2.000805  2018.0   2019.00    2021.0    2023.0      2024.0
registered_users  18294.0  376183.604624  863905.925064     1.0  20261.75  101599.0  359706.0  18127475.0

df_top_user_years Summary:
                  count         mean           std      min        25%        50%         75%         max
year              840.0     2021.000  2.001192e+00   2018.0    2019.00     2021.0      2023.0      2024.0
registered_users  840.0  9342127.825  1.313515e+07  68098.0  586900.75  3725017.0  12806250.5  71807805.0

In [ ]:
import os
'''


# path to save the renamed files
save_path = r"C:\Users\Admin\Desktop\sb\ds_ml\internship\labmentix\project_2\preprocessed_data_frames\other_df"

# save each df with modified name
for name, df in dfs.items():
    new_name = f"{name}_new"   # or "_1" if you prefer
    df.to_csv(os.path.join(save_path, f"{new_name}.csv"), index=False)
    print(f"Saved: {new_name}.csv")
    
    
    '''

Saved: df_aggregated_insurance_state_new.csv
Saved: df_aggregated_insurance_years_new.csv
Saved: df_aggregated_transaction_state_new.csv
Saved: df_aggregated_transaction_years_new.csv
Saved: df_aggregated_user_state_new.csv
Saved: df_aggregated_user_years_new.csv
Saved: df_map_insurance_hover_state_new.csv
Saved: df_map_insurance_hover_years_new.csv
Saved: df_map_transaction_state_new.csv
Saved: df_map_transaction_years_new.csv
Saved: df_map_user_state_new.csv
Saved: df_map_user_years_new.csv
Saved: df_top_insurance_state_new.csv
Saved: df_top_insurance_years_new.csv
Saved: df_top_transaction_state_new.csv
Saved: df_top_transaction_years_new.csv
Saved: df_top_user_state_new.csv
Saved: df_top_user_years_new.csv

In [ ]:
df_state = pd.read_csv(os.path.join(path, "df_map_insurance_country_state.csv"))
df_years = pd.read_csv(os.path.join(path, "df_map_insurance_country_years.csv"))

In [57]:
print(df_state.info(),'\n')
print(df_years.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1043137 entries, 0 to 1043136
Data columns (total 6 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   lat     1043137 non-null  float64
 1   lng     1043137 non-null  float64
 2   metric  1043137 non-null  float64
 3   label   1043137 non-null  object
 4   state   1043137 non-null  object
 5   year    1043137 non-null  int64
dtypes: float64(3), int64(1), object(2)
memory usage: 47.8+ MB
None

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 387212 entries, 0 to 387211
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   lat     387212 non-null  float64
 1   lng     387212 non-null  float64
 2   metric  387212 non-null  float64
 3   label   387209 non-null  object
 4   year    387212 non-null  int64
dtypes: float64(3), int64(1), object(1)
memory usage: 14.8+ MB
None

In [60]:
df_state.sample(5)

              lat        lng  metric               label           state  year
376267  17.722548  77.498875     1.0      bidar district       karnataka  2024
735232  26.543444  76.137794     6.0     jaipur district       rajasthan  2024
475685  23.722309  75.393681     1.0     ratlam district  madhya-pradesh  2024
40882   13.973280  77.853880     3.0  anantapur district  andhra-pradesh  2023
705550  26.220584  75.533493     3.0       tonk district       rajasthan  2023

In [61]:
df_years.sample(5)

              lat        lng  metric        label  year
320158  26.533309  77.384120     7.0    rajasthan  2023
319022  17.363385  80.460464     8.0    telangana  2023
363555  25.275630  87.938382    52.0  west bengal  2024
324549  25.251286  86.098825     4.0        bihar  2023
232421  17.134243  80.815632     1.0    telangana  2022

In [ ]:
# --- Basic preprocessing ---
for df in [df_state, df_years]:
    # strip spaces, lowercase, replace spaces with underscores
    df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

    # drop duplicates
    df.drop_duplicates(inplace=True)

In [65]:
for df in [df_state, df_years]:
    print(df.shape)

(997744, 6)
(381088, 5)

In [66]:
# Example: rename specific columns in df_state
df_state.rename(columns={
    'lat': 'latitude',
    'lng': 'longitude',
    'metric': 'count',
    'label': 'district'
}, inplace=True)

# Example: rename in df_years (adjust based on your actual column names)
df_years.rename(columns={
    'lat': 'latitude',
    'lng': 'longitude',
    'metric': 'count',
    'label': 'state'
}, inplace=True)

In [70]:
df_state.sample(2)

         latitude  longitude  count          district           state  year
643455  30.549125  74.141613    1.0  fazilka district          punjab  2022
477610  22.849888  75.393681    6.0     dhar district  madhya-pradesh  2024

In [71]:
df_years.sample(2)

         latitude  longitude  count      state  year
104149  29.956743  74.352882    4.0     punjab  2021
265652  12.831870  78.207737   11.0  karnataka  2023

In [ ]:
'''


save_path = r"C:\Users\Admin\Desktop\sb\ds_ml\internship\labmentix\project_2\preprocessed_data_frames\map_df"


df_state.to_csv(os.path.join(save_path, "df_map_insurance_country_state_cleaned.csv"), index=False)
df_years.to_csv(os.path.join(save_path, "df_map_insurance_country_years_cleaned.csv"), index=False)


'''

In [73]:
# change df_map_insurance_hover_state, df_map_insurance_hover_years names into just 
# df_map_insurance_state, df_map_insurance_years ... to make it easier for streamlit code .. 
# also changing manually is the simplest way